[tool.poetry]
name = "musical"
version = "1.1.0"
description = "MuSiCal is a comprehensive toolkit for mutational signature analysis"
authors = ["Hu Jin, Doga Gulhan"]
maintainers = [
    "Hu Jin <hu_jin@hms.harvard.edu>",
    "Doga Gulhan <doga_gulhan@hms.harvard.edu>",
    "Benedikt Geiger <benedikt_geiger@hms.harvard.edu>",
]
packages = [{ include = "musical", from = "src" }]

readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
matplotlib = "^3.7.1"
numpy = "^1.24.3"
pandas = "^1.5.3"
scikit-learn = "^1.3.0"
scipy = "^1.10.1"
salamander-learn = "^0.4.1"
seaborn = "^0.13.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pytest = "^7.4.2"
pre-commit = "^3.4.0"
tox = "^4.11.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
